spring.application.name=EduManager

spring.datasource.url=jdbc:postgresql://localhost/edumanager-db
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.expiracao = 10
spring.secret = "jgnskgjsdgjsdgjsbngjkswbgjs"
spring.emissor = "ray"


springdoc.swagger-ui.tagsSorter=alpha